package com.bornander.tools.sheetcreator;

public class SheetPropertiesPanel extends javax.swing.JPanel {

    public SheetPropertiesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTileSize = new javax.swing.JLabel();
        spinnerTileSize = new javax.swing.JSpinner();
        labelTilePadding = new javax.swing.JLabel();
        spinnerTilePadding = new javax.swing.JSpinner();

        labelTileSize.setText("Tile size:");

        spinnerTileSize.setModel(new javax.swing.SpinnerNumberModel(32, 1, 1024, 1));
        spinnerTileSize.setValue(32);

        labelTilePadding.setText("Tile padding:");

        spinnerTilePadding.setModel(new javax.swing.SpinnerNumberModel(1, 0, 4, 1));
        spinnerTilePadding.setValue(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTilePadding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTileSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerTileSize, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(spinnerTilePadding))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTileSize)
                    .addComponent(spinnerTileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTilePadding)
                    .addComponent(spinnerTilePadding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTilePadding;
    private javax.swing.JLabel labelTileSize;
    private javax.swing.JSpinner spinnerTilePadding;
    private javax.swing.JSpinner spinnerTileSize;
    // End of variables declaration//GEN-END:variables

    int getTileSize() {
        return (int) spinnerTileSize.getValue();
    }

    int getTilePadding() {
        return (int) spinnerTilePadding.getValue();
    }
}
